### ISSUE TITLE
Error connection to Windows server 2016 RDS

### ISSUE THREAD

**Issue by civic9** [GoSecure/pyrdp#104]
Hi,

I just added to my windows server 2016 Remote Desktop Services Role with two services: Licensing and Session Host.

Now I can't connect through pyrdp. It was all fine before adding RDS Role. Any ideas? .

```
[2019-05-09 16:52:52,439] - INFO - Thomas821467 - pyrdp.mitm.connections.security - Client Info: username = 'administrator\x00', password = '\x
00', domain = '\x00', clientAddress = '....\x00'
[2019-05-09 16:52:52,439] - DEBUG - Thomas821467 - pyrdp.mitm.connections.security - Sending ClientInfoPDU{'payload': b'', 'codePage': 68486165
, 'flags': 213299, 'domain': '\x00', 'username': 'administrator\x00', 'password': '\x00', 'alternateShell': '\x00', 'workingDir': '\x00', 'extr
aInfo': ClientExtraInfo{'payload': b'', 'clientAddressFamily': 2, 'clientAddress': ..., 'clientDir': ...', 'clientTimeZone': b'...', 'clientSessionID': 1, 'performanceFlags': 15, 'autoReconnectCookie': b'', 'dynamicDSTTimeZoneKeyName': b'...', 'dynamicDaylightTimeDisabled': False}}
[2019-05-09 16:52:52,439] - DEBUG - Thomas821467 - pyrdp.mitm.connections.client.mcs - Received MCSPDUType.SEND_DATA_REQUEST
[2019-05-09 16:52:52,445] - DEBUG - Thomas821467 - pyrdp.mitm.connections.server.x224 - Received X224PDUType.X224_TPDU_DATA
[2019-05-09 16:52:52,445] - DEBUG - Thomas821467 - pyrdp.mitm.connections.server.security - Received licensing data
[2019-05-09 16:52:52,445] - DEBUG - Thomas821467 - pyrdp.mitm.connections.server.mcs - Received MCSPDUType.SEND_DATA_INDICATION
[2019-05-09 16:52:52,703] - DEBUG - Thomas821467 - pyrdp.mitm.connections.client.x224 - Received X224PDUType.X224_TPDU_DATA
[2019-05-09 16:52:52,703] - ERROR - GLOBAL - pyrdp - 9 is not a valid SlowPathPDUType
Traceback (most recent call last):
  File "/pyrdp/pyrdp/layer/tcp.py", line 90, in dataReceived
    self.recv(data)
  File "/pyrdp/pyrdp/layer/layer.py", line 143, in recv
    self.pduReceived(pdu)
  File "/pyrdp/pyrdp/layer/layer.py", line 198, in pduReceived
    self.next.recv(pdu.payload)
  File "/pyrdp/pyrdp/layer/segmentation.py", line 79, in recv
    layer.recv(forwarded)
  File "/pyrdp/pyrdp/layer/buffered.py", line 55, in recv
    self.pduReceived(pdu)
  File "/pyrdp/pyrdp/layer/layer.py", line 198, in pduReceived
    self.next.recv(pdu.payload)
  File "/pyrdp/pyrdp/layer/layer.py", line 143, in recv
    self.pduReceived(pdu)
  File "/pyrdp/pyrdp/layer/layer.py", line 198, in pduReceived
    self.next.recv(pdu.payload)
  File "/pyrdp/pyrdp/layer/layer.py", line 143, in recv
    self.pduReceived(pdu)
  File "/pyrdp/pyrdp/layer/layer.py", line 110, in pduReceived
    self.observer.onPDUReceived(pdu)
  File "/pyrdp/pyrdp/core/observer.py", line 82, in __call__
    self.composite.doCall(self.item, args, kwargs)
  File "/pyrdp/pyrdp/core/observer.py", line 56, in doCall
    getattr(observer, item)(*args, **kwargs)
  File "/pyrdp/pyrdp/layer/layer.py", line 48, in onPDUReceived
    self.handlers[pdu.header](pdu)
  File "/pyrdp/pyrdp/mitm/MCSMITM.py", line 229, in onSendDataRequest
    self.clientChannels[pdu.channelID].recv(pdu.payload)
  File "/pyrdp/pyrdp/mcs/channel.py", line 33, in recv
    self.next.recv(data)
  File "/pyrdp/pyrdp/layer/rdp/security.py", line 140, in recv
    self.next.recv(data)
  File "/pyrdp/pyrdp/layer/layer.py", line 142, in recv
    pdu = self.mainParser.parse(data)
  File "/pyrdp/pyrdp/parser/rdp/slowpath.py", line 59, in parse
    header = self.parseShareControlHeader(stream)
  File "/pyrdp/pyrdp/parser/rdp/slowpath.py", line 109, in parseShareControlHeader
    return ShareControlHeader(SlowPathPDUType(pduType & 0xf), (pduType >> 4), source)
  File "/usr/lib/python3.6/enum.py", line 293, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 535, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 548, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 9 is not a valid SlowPathPDUType
....
[2019-05-09 16:52:52,704] - ERROR - GLOBAL - pyrdp - Exception occurred when receiving: ....
[2019-05-09 16:52:52,705] - INFO - Thomas821467 - pyrdp.mitm.connections.tcp - Client connection closed. Connection to the other side was lost in a non-clean fashion: Connection lost.
```

Sometimes it is another SlowPathPduType:
```
[2019-05-09 16:43:29,166] - ERROR - GLOBAL - pyrdp - 15 is not a valid SlowPathPDUType
```

**Comment by xshill** [comment]
I remember having strange issues like this when some sort of cryptographic bug was happening. Are these connections made with TLS or with the built-in RDP crypto (RC4)?

**Comment by civic9** [comment]
Ah, thanks for the tip.
Looks like adding session host features changes server's cert and priv key.
And running pyrdp with previous cert/key gives results as a above.

**Comment by civic9** [comment]
Sorry, I was too fast. Nope, that didn't resolve the issue.
Yes, connections are made with TLS.

**Comment by Res260** [comment]
Can you share the complete logs from the first packets of the connection, as well as a PCAP of the tcp connection on port 3389? That would be really helpful for us to troubleshoot the actual problem :)

**Comment by civic9** [comment]
Logs and pcap attached.
Note - my windows server responds on port 3001, so traffic to port 3001 is captured.
[logs.zip](https://github.com/GoSecure/pyrdp/files/3169588/logs.zip)

**Comment by Res260** [comment]
Thanks. I'll have a look when I have time!

**Comment by Pourliver** [comment]
Any updates? I've been testing a few different OSes with PyRDP, and Win Server 2016 always give me this error. I'll look into it as well.

**Comment by Res260** [comment]
Oops forgot to check, I'll put a reminder on. I don't have a win server 2016 machine setup though, I'll start by analyzing the pcap.

**Comment by Pourliver** [comment]
I confirm that this error persists on Windows Server 2012 with RDS.

**Comment by Pourliver** [comment]
At this point, even though I looked into licensing issue, I'm pretty sure its a licensing thing that is being mishandled by PyRDP. Using the /admin switch makes mstsc.exe not require a CAL.

**Comment by Pourliver** [comment]
Fixed in #118

**Comment by excitoon** [comment]
@civic9

```
[2019-05-09 16:43:29,166] - ERROR - GLOBAL - pyrdp - 15 is not a valid SlowPathPDUType
```

This error is still here, and it looks like we have it "by design". Due to MITM nature of PyRDP, you can't guarantee order of processing for packets coming in two directions, it is even worse in Python, longer packets you have, longer processing time will be.
